/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Comisiones.java
 *
 * Created on Jun 21, 2015, 8:52:39 PM
 */
package Recursos_Humanos;

import Clases.Fechas;
import Clases.Secretaria;
import Clases.conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import org.jvnet.substance.SubstanceLookAndFeel;

/**
 *
 * @author bernardo
 */
public class Comisiones extends javax.swing.JFrame {
    private Connection cn;

    /** Creates new form Comisiones */
    public Comisiones() {
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false); 
        setTitle("Calcular comisiones");
        this.getContentPane().setBackground(new java.awt.Color(0, 0, 102));
        Secretaria clase = new Secretaria();
        clase.Propiedades_vendidas_y_no();
    }
    
    private void actualizar(){
        DefaultTableModel modelo=(DefaultTableModel) tabla_comisiones.getModel();
        int filas=tabla_comisiones.getRowCount();
        for (int i = 0;filas>i; i++) {
            modelo.removeRow(0);
        }
        Secretaria frm4 = new Secretaria();
        frm4.Propiedades_vendidas_y_no();
    }
    
    private void CalcularComision(){
        Calendar cal = Calendar.getInstance();
        java.util.Date Ahora = new java.util.Date();
        cal.set(Ahora.getYear(), Ahora.getMonth(), Ahora.getDate());
        java.util.Date F1 = new java.util.Date();
        F1.setDate(cal.getActualMinimum(Calendar.DAY_OF_MONTH));
        java.util.Date F2 = new java.util.Date();
        F2.setDate(cal.getActualMaximum(Calendar.DAY_OF_MONTH));
        SimpleDateFormat formateador = new SimpleDateFormat("yyyy-MM-dd");
        String Inicial = formateador.format(F1);
        String Final = formateador.format(F2);
        try{
            String sql = "Select sum(Precio_base) suma from propiedad,Agenda_ventas,empleado where Agenda_ventas.id_propiedad = propiedad.id_propiedad and Agenda_ventas.id_empleado = empleado.id_empleado and Agenda_ventas.id_empleado = " + Secretaria.ID_emp + " and Agenda_ventas.id_estadoAV = 3 and fecha between  '" + Inicial + "' and '" + Final + "'";
            conexion con = new conexion();
            cn = con.conexion();
            PreparedStatement cmd = cn.prepareStatement(sql);
            ResultSet rs = cmd.executeQuery();
            Double Total = 0.00;
            if(rs.next()){
                Total = rs.getDouble(1);
                Total = Total * 0.06;
            }
            cmd.close();
            cn.close();
            txtComision.setText(Total.toString());
            
        }
        catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }
   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_comisiones = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cmbFiltro = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtComision = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla_comisiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "codigo", "Cliente", "Propiedad", "Precio base", "Fecha", "Hora", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_comisiones.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabla_comisiones);
        if (tabla_comisiones.getColumnModel().getColumnCount() > 0) {
            tabla_comisiones.getColumnModel().getColumn(0).setResizable(false);
            tabla_comisiones.getColumnModel().getColumn(1).setResizable(false);
            tabla_comisiones.getColumnModel().getColumn(2).setResizable(false);
            tabla_comisiones.getColumnModel().getColumn(3).setResizable(false);
            tabla_comisiones.getColumnModel().getColumn(4).setResizable(false);
            tabla_comisiones.getColumnModel().getColumn(5).setResizable(false);
            tabla_comisiones.getColumnModel().getColumn(6).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Visualizar ventas segun:");

        cmbFiltro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Seleccione uno-", "Ambas", "Vendido", "No vendido" }));
        cmbFiltro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbFiltroItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Comisiones de este mes por las ventas del empleado:");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Emplead@:");

        lblNombre.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre");

        txtComision.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("$");

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("Principal");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtComision, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNombre)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(txtComision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        empleado frm = new empleado();
        Secretaria.ID_emp = 0;
        frm.show();
        this.hide();
}//GEN-LAST:event_jMenu1MouseClicked

private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

}//GEN-LAST:event_jMenu1ActionPerformed

private void cmbFiltroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbFiltroItemStateChanged
// TODO add your handling code here:
    int indice = cmbFiltro.getSelectedIndex();
        if(indice == 0 || indice == 1){
            
            Secretaria.Cambiado = "Agenda_ventas.id_estadoAV = 3 or Agenda_ventas.id_estadoAV = 4";
            actualizar();
        } 
        else if(indice == 2)
        {
            Secretaria.Cambiado = "Agenda_ventas.id_estadoAV = 3";
            actualizar();
        }
        else if(indice == 3)
        {
            Secretaria.Cambiado = "Agenda_ventas.id_estadoAV = 4";
            actualizar();
        }
}//GEN-LAST:event_cmbFiltroItemStateChanged

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:C
    CalcularComision();
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Comisiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Comisiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Comisiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Comisiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                 JFrame.setDefaultLookAndFeelDecorated(true);
        SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.MistAquaSkin");    //seaplica la libreria de look and feel
                new Comisiones().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbFiltro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblNombre;
    public static javax.swing.JTable tabla_comisiones;
    private javax.swing.JTextField txtComision;
    // End of variables declaration//GEN-END:variables
}
