/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vendedor;

import Clases.Secretaria;
import Clases.conexion;
import ptc.*;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jvnet.substance.SubstanceLookAndFeel;

/**
 *
 * @author Walter
 */
public class Agenda extends javax.swing.JFrame {
    private Connection cn;
    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Agenda");
        this.setResizable(false);
        this.getContentPane().setBackground(new java.awt.Color(0, 0, 102));
        Secretaria clase = new Secretaria();
        clase.agenda_empleado();
        
    }
    
    private void actualizar(){
        DefaultTableModel modelo=(DefaultTableModel) tabla_agenda.getModel();
        int filas=tabla_agenda.getRowCount();
        for (int i = 0;filas>i; i++) {
            modelo.removeRow(0);
        }
        Secretaria frm4 = new Secretaria();
        frm4.agenda_empleado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_agenda = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla_agenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Cliente", "Propiedad", "Precio base", "Fecha", "Hora", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_agenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_agendaMouseClicked(evt);
            }
        });
        tabla_agenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabla_agendaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_agenda);
        if (tabla_agenda.getColumnModel().getColumnCount() > 0) {
            tabla_agenda.getColumnModel().getColumn(0).setResizable(false);
            tabla_agenda.getColumnModel().getColumn(1).setResizable(false);
            tabla_agenda.getColumnModel().getColumn(2).setResizable(false);
            tabla_agenda.getColumnModel().getColumn(3).setResizable(false);
            tabla_agenda.getColumnModel().getColumn(4).setResizable(false);
            tabla_agenda.getColumnModel().getColumn(5).setResizable(false);
            tabla_agenda.getColumnModel().getColumn(6).setResizable(false);
        }

        jMenu1.setText("Principal");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Archivo");

        jMenuItem1.setText("Vendido");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("No vendido");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        PrincipalVendedor frm = new PrincipalVendedor();
        frm.show();
        this.hide();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private static Integer ID_agenda = 0;
    private void tabla_agendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_agendaMouseClicked
        ID_agenda = (Integer) tabla_agenda.getValueAt(tabla_agenda.getSelectedRow(), 0);
    }//GEN-LAST:event_tabla_agendaMouseClicked

    private void tabla_agendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabla_agendaKeyPressed
        
    }//GEN-LAST:event_tabla_agendaKeyPressed

private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
// TODO add your handling code here:
    if(ID_agenda != 0){
        int verificar = JOptionPane.showConfirmDialog(this, "¿Esta seguro de poner el estado de vendido?, no se podrá cambiar despues. Sabiendo esto, ¿Desea continuar?", "Atencion",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(verificar == 0){
            Secretaria obj = new Secretaria();
            obj.setCodigo(ID_agenda);
            obj.setTipo(3);
            if(obj.Modificar_agendaEmpleado()){
                actualizar();
                try{
                    String sql = "update propiedad set id_estadopropi = 2 where id_propiedad = (select id_propiedad from Agenda_ventas where id_agenda = " + ID_agenda + ");";
                    conexion con = new conexion();
                    cn = con.conexion();
                    PreparedStatement cmd = cn.prepareStatement(sql);
                    if(!cmd.execute()){
                        JOptionPane.showMessageDialog(this, "La propiedad ha dejado de estar disponible. Datos guardados exitosamente");
                    }
                    
                }catch(Exception ex){}
            }
        }
        ID_agenda = 0;
    }
    
}//GEN-LAST:event_jMenuItem1ActionPerformed

private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
// TODO add your handling code here:
    if(ID_agenda != 0){
        int verificar = JOptionPane.showConfirmDialog(this, "¿Esta seguro de poner el estado de NO vendido?, no se podrá cambiar despues. Sabiendo esto, ¿Desea continuar?", "Atencion",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(verificar == 0){
            Secretaria obj = new Secretaria();
            obj.setCodigo(ID_agenda);
            obj.setTipo(4);
            if(obj.Modificar_agendaEmpleado()){
                actualizar();
                
                JOptionPane.showMessageDialog(this, "Datos modificados correctamente");
            }
        }
        ID_agenda = 0;
    }
}//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                                JFrame.setDefaultLookAndFeelDecorated(true);
        SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.MistAquaSkin");    //seaplica la libreria de look and feel
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tabla_agenda;
    // End of variables declaration//GEN-END:variables
}
