/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vendedor;
import Clases.conexion;
import Vendedor.PrincipalVendedor;
import Clases.mth_cliente;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.*;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import org.jvnet.substance.SubstanceLookAndFeel;
import ptc.Login;
/**
 *
 * @author kevin Vásquez
 */
public class Clientes extends javax.swing.JFrame 
{
    private Connection cn;
    DefaultTableModel model;
    
    public void Sletras(JTextField a){
        a.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e){
            char c=e.getKeyChar();
            if(!Character.isLetter(c) && !Character.isSpaceChar(c)){
                getToolkit().beep();
                e.consume();
            }
        }
      
        });
    }
    
    public boolean Email(String email){
       Pattern pat = null;
       Matcher mat = null;
       pat = Pattern.compile("^[A-Za-z0-9._%-]+@[A-Za-z0-9.-]+\\.[a-zA-Z]{2,4}$");
        mat = pat.matcher(email);
        if(mat.find()){
            return true;
        }else{
            return false;
        }
    }


    /**
     * Creates new form Clientes
     */
    public Clientes() 
    {
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Empleados");
        this.setResizable(false);
        this.getContentPane().setBackground(new java.awt.Color(0, 0, 102));
        Sletras(textnombre);
        Sletras(textapellido);
        
        
        mth_cliente tabla = new mth_cliente();
        tabla.tabla_clientes();
       
        
    }
    
    private void limpiar(){
        textid.setText(null);
        textnombre.setText(null);
        textapellido.setText(null);
        txtdui.setText(null);
        txtnit.setText(null);
        txttelefono.setText(null);
        txtCorreo.setText(null);
    }
    
    private void actualizar(){
        DefaultTableModel modelo=(DefaultTableModel) tcliente.getModel();
        int filas=tcliente.getRowCount();
        for (int i = 0;filas>i; i++) {
            modelo.removeRow(0);
        }
        mth_cliente frm4 = new mth_cliente();
        frm4.tabla_clientes();
        frm4.tabla_clientes();
        limpiar();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tcliente = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtdui = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txttelefono = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        txtnit = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textapellido = new javax.swing.JTextField();
        textid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textnombre = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tcliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombres", "Apellidos", "DUI", "NIT", "Telefono", "Correo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tcliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tclienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tcliente);
        if (tcliente.getColumnModel().getColumnCount() > 0) {
            tcliente.getColumnModel().getColumn(0).setResizable(false);
            tcliente.getColumnModel().getColumn(1).setResizable(false);
            tcliente.getColumnModel().getColumn(2).setResizable(false);
            tcliente.getColumnModel().getColumn(3).setResizable(false);
            tcliente.getColumnModel().getColumn(4).setResizable(false);
            tcliente.getColumnModel().getColumn(5).setResizable(false);
            tcliente.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setOpaque(false);

        try {
            txtdui.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtdui.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtduiFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NIT");

        try {
            txttelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txttelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txttelefonoFocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telefono");

        try {
            txtnit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-######-###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtnit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnitFocusLost(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Apellidos");

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Codigo:");

        textid.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombres");

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Correo:");

        textnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textnombreKeyTyped(evt);
            }
        });

        txtCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCorreoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCorreoFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DUI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttelefono)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textnombre)
                                .addComponent(textapellido)
                                .addComponent(textid, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtdui, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtnit)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtdui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/1434841655_f-cross_256.png"))); // NOI18N
        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/1434664469_edit-clear.png"))); // NOI18N
        jButton5.setText("Nuevo");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/1434608001_save_as-2.png"))); // NOI18N
        jButton3.setText("Guardar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/1434857547_001_45.png"))); // NOI18N
        jButton6.setText("Modificar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/1434854150_exit.png"))); // NOI18N
        jMenu1.setText("Cerrar sesion");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/1434853539_go-back.png"))); // NOI18N
        jMenu3.setText("Regresar");
        jMenu3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 153, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean ValidarDUI(){
        boolean resp = false;
        if(!txtdui.getText().isEmpty())
    {
        try {
            conexion con = new conexion();
            cn = con.conexion();
            int ID = 0;
            PreparedStatement cmd = cn.prepareStatement("Select * from cliente where DUI = '" + txtdui.getText() + "'");
            ResultSet rs = cmd.executeQuery();
            if(rs.next())
            {
                if(!textid.getText().isEmpty()){
                    ID = rs.getInt(1);
                if(ID != Integer.parseInt(textid.getText()))
                {
                    resp = true;
                    JOptionPane.showMessageDialog(this, "El DUI ingresado ya existe, por favor intente con otro");
                    txtdui.setText(null);
                }
                }
                else
                {
                    resp = true;
                    JOptionPane.showMessageDialog(this, "El DUI ingresado ya existe, por favor intente con otro");
                    txtdui.setText(null);
                }
                
            }
            cmd.close();
            cn.close();
            
            } catch (SQLException ex) {
                ex.getMessage();
            }
    }
        return resp;
    }
    
    private boolean ValidarNIT(){
        boolean resp = false;
        if(!txtnit.getText().isEmpty())
    {
        try {
            conexion con = new conexion();
            int ID = 0;
            cn = con.conexion();
            PreparedStatement cmd = cn.prepareStatement("Select * from cliente where NIT = '" + txtnit.getText() + "'");
            ResultSet rs = cmd.executeQuery();
            if(rs.next())
            {
                if(!textid.getText().isEmpty()){
                    ID = rs.getInt(1);
                if(ID != Integer.parseInt(textid.getText()))
                {
                    resp = true;
                    JOptionPane.showMessageDialog(this, "El NIT ingresado ya existe, por favor intente con otro");
                    txtnit.setText(null);
                }
                }
                else
                {
                    resp = true;
                    JOptionPane.showMessageDialog(this, "El NIT ingresado ya existe, por favor intente con otro");
                    txtnit.setText(null);
                }
                
                
            }
            cmd.close();
            cn.close();
            
            } catch (SQLException ex) {
                ex.getMessage();
            }
    }
        return resp;
    }
    
    private boolean ValidarTel(){
        boolean resp = false;
        if(!txttelefono.getText().isEmpty())
    {
        try {
            conexion con = new conexion();
            cn = con.conexion();
            int ID = 0;
            PreparedStatement cmd = cn.prepareStatement("Select * from cliente where Telefono = '" + txttelefono.getText() + "'");
            ResultSet rs = cmd.executeQuery();
            if(rs.next())
            {
                if(!textid.getText().isEmpty()){
                    ID = rs.getInt(1);
                if(ID != Integer.parseInt(textid.getText()))
                {
                    resp = true;
                    JOptionPane.showMessageDialog(this, "El Telefono ingresado ya existe, por favor intente con otro");
                    txttelefono.setText(null);
                }
                }
                else
                {
                    resp = true;
                    JOptionPane.showMessageDialog(this, "El Telefono ingresado ya existe, por favor intente con otro");
                    txttelefono.setText(null);
                }
            }
            cmd.close();
            cn.close();
            
            } catch (SQLException ex) {
                ex.getMessage();
            }
    }
        return resp;
    }
    
    private boolean ValidarCorreo(){
        boolean resp = false;
        if(!txtCorreo.getText().isEmpty())
    {
        try {
            conexion con = new conexion();
            cn = con.conexion();
            int ID = 0;
            PreparedStatement cmd = cn.prepareStatement("Select * from cliente where correo = '" + txtCorreo.getText() + "'");
            ResultSet rs = cmd.executeQuery();
            if(rs.next())
            {
                if(!textid.getText().isEmpty()){
                    ID = rs.getInt(1);
                if(ID != Integer.parseInt(textid.getText()))
                {
                    resp = true;
                    JOptionPane.showMessageDialog(this, "El Correo ingresado ya existe, por favor intente con otro");
                    txtCorreo.setText(null);
                }
                }
                else
                {
                    resp = true;
                    JOptionPane.showMessageDialog(this, "El Correo ingresado ya existe, por favor intente con otro");
                    txtCorreo.setText(null);
                }
            }
            else
            {
                if(Email(txtCorreo.getText())){
                    System.out.println("Correcto");
                }
                else{
                    JOptionPane.showMessageDialog(this, "Por favor escriba su correo de forma correcta");
                    txtCorreo.setText(null);
                }

            }
            cmd.close();
            cn.close();
            
            } catch (SQLException ex) {
                ex.getMessage();
            }
    }
        return resp;
    }
    
    
   
    

    
    private void textnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textnombreKeyTyped
        
    }//GEN-LAST:event_textnombreKeyTyped

private void txtduiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtduiFocusLost
// TODO add your handling code here:
    
}//GEN-LAST:event_txtduiFocusLost

private void txtnitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnitFocusLost
// TODO add your handling code here:
    
}//GEN-LAST:event_txtnitFocusLost

private void txttelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttelefonoFocusLost
// TODO add your handling code here:
    
}//GEN-LAST:event_txttelefonoFocusLost

private void txtCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoFocusLost
// TODO add your handling code here:{}
    if(!txtCorreo.getText().isEmpty()){
        if(Email(txtCorreo.getText())){
                    System.out.println("Correcto");
                }
                else{
                    JOptionPane.showMessageDialog(this, "Por favor escriba su correo de forma correcta");
                    txtCorreo.setText(null);
                }
    }
    
}//GEN-LAST:event_txtCorreoFocusLost

private void tclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tclienteMouseClicked
// TODO add your handling code here:
    Integer ID = (Integer) tcliente.getValueAt(tcliente.getSelectedRow(), 0);
    String Nombres = (String) tcliente.getValueAt(tcliente.getSelectedRow(), 1);
    String Apellidos = (String) tcliente.getValueAt(tcliente.getSelectedRow(), 2);
    String DUI = (String) tcliente.getValueAt(tcliente.getSelectedRow(), 3);
    String NIT = (String) tcliente.getValueAt(tcliente.getSelectedRow(), 4);
    String Telefono = (String) tcliente.getValueAt(tcliente.getSelectedRow(), 5);
    String Correo = (String) tcliente.getValueAt(tcliente.getSelectedRow(), 6);
    
    textid.setText(ID.toString());
    textnombre.setText(Nombres);
    textapellido.setText(Apellidos);
    txtdui.setText(DUI);
    txtnit.setText(NIT);
    txttelefono.setText(Telefono);
    txtCorreo.setText(Correo);
    
}//GEN-LAST:event_tclienteMouseClicked

private void txtCorreoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoFocusGained
// TODO add your handling code here:
}//GEN-LAST:event_txtCorreoFocusGained

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(!textid.getText().isEmpty()){
        mth_cliente obj = new mth_cliente();
        obj.setCodigo(Integer.parseInt(textid.getText()));
        int eliminar = JOptionPane.showConfirmDialog(this, "¿Esta seguro que desea eliminar los datos?", "Atencion",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(eliminar == 0)
        {
            if(obj.eliminar())
            {
                actualizar();
                JOptionPane.showMessageDialog(this, "Datos Eliminados");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Error al eliminar los datos");
            }
        }
        
    }
    else
    {
        JOptionPane.showMessageDialog(this, "Por favor llene todos los campos");
    }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       // TODO add your handling code here:
        if(!textnombre.getText().isEmpty() && !textapellido.getText().isEmpty() && !txtdui.getText().isEmpty() && !txtnit.getText().isEmpty() && !txttelefono.getText().isEmpty() && !txtCorreo.getText().isEmpty() && !ValidarDUI() && !ValidarNIT() && !ValidarTel() && !ValidarCorreo()){
        mth_cliente obj = new mth_cliente();
        obj.setNombre(textnombre.getText());
        obj.setApellido(textapellido.getText());
        obj.setDUI((txtdui.getText())); 
        obj.setNIT((txtnit.getText()));
        obj.setTelefono((txttelefono.getText()));
        obj.setCorreo(txtCorreo.getText());
        if(obj.guardar())
        {
            actualizar();
            JOptionPane.showMessageDialog(this, "Datos Guardados");
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Error al guardar los datos, asegurece de que no hayan datos repetidos y vuelva a intentarlo");
        }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Por favor llene todos los campos");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(!textid.getText().isEmpty() &&!textnombre.getText().isEmpty() && !textapellido.getText().isEmpty() && !txtdui.getText().isEmpty() && !txtnit.getText().isEmpty() && !txttelefono.getText().isEmpty() && !txtCorreo.getText().isEmpty() && !ValidarDUI() && !ValidarNIT() && !ValidarTel() && !ValidarCorreo()){
        mth_cliente obj = new mth_cliente();
        obj.setCodigo(Integer.parseInt(textid.getText()));
        obj.setNombre(textnombre.getText());
        obj.setApellido(textapellido.getText());
        obj.setDUI((txtdui.getText())); 
        obj.setNIT((txtnit.getText()));
        obj.setTelefono((txttelefono.getText()));
        obj.setCorreo(txtCorreo.getText());
        if(obj.modificar())
        {
            actualizar();
            JOptionPane.showMessageDialog(this, "Datos modificados");
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Error al modificar los datos, asegurece de que no haya ningun dato repetido y vuelva a intentarlo");
        }
    }
    else
    {
        JOptionPane.showMessageDialog(this, "Por favor llene todos los campos");
    }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        PrincipalVendedor frm = new PrincipalVendedor();
        frm.show();
        this.hide();
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed

    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        Login frm = new Login();
        frm.show();
        this.hide();
    }//GEN-LAST:event_jMenu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                                JFrame.setDefaultLookAndFeelDecorated(true);
        SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.MistAquaSkin");    //seaplica la libreria de look and feel
                new Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tcliente;
    private javax.swing.JTextField textapellido;
    private javax.swing.JTextField textid;
    private javax.swing.JTextField textnombre;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JFormattedTextField txtdui;
    private javax.swing.JFormattedTextField txtnit;
    private javax.swing.JFormattedTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}

